import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Fab from '@mui/material/Fab';
import MailOutlineIcon from '@mui/icons-material/MailOutline';
import About from './components/About'
import Contact from './components/Contact'
import Projects from './components/Projects'
import Cover from './components/Cover'
import Navbar from './components/Navbar'
import bgimg from '../public/images/basement.png'
import codingGif from '../public/images/coding.gif'
import { Parallax, ParallaxLayer } from '@react-spring/parallax'
import { createTheme, ThemeProvider } from '@mui/material/styles';
import { useEffect, useState } from 'react';

const theme = createTheme({
  status: {
    danger: '#e53e3e',
  },
  palette: {
    primary: {
      main: '#8AD88F',
      darker: '#053e85',
    },
    neutral: {
      main: '#64748B',
      contrastText: '#fff',
    },
  },
});



export default function Home() {

  const [winHeight, setWinHeight] = useState(0)
  useEffect(() => {
    const windowHeight = window.innerHeight;
    console.log(windowHeight)
    setWinHeight(windowHeight)
  }, [])

  function jumpTo(section) {
    // console.log(section);
    const elem = document.getElementById(section)
    elem.scrollIntoView()
    // var url = location.href;
    // location.href = "#"+section;                 
    // history.replaceState(null,null,url);
  }
  // 
  return (
    <div className={styles.container} style={{ height: "auto" }}>
      <Head>
        <title>Devtoti Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <style>
          @import url('https://fonts.googleapis.com/css2?family=Roboto+Flex:opsz,wght@8..144,400;8..144,500;8..144,600&display=swap');
        </style>
      </Head>
      <Navbar />
      <section>
        <Cover />
      </section>
      <section>
        <About />
      </section>
      <section>
        <Projects />
      </section>
      <section>
        <Contact />
      </section>
    </div>
  )
}

      // <main className={styles.main}>
      //   <Parallax pages={2.65}
      //     style={{
      //       // backgroundColor: 'coral',
      //     }}>
      //     <ParallaxLayer
      //       offseet={0}
      //       factor={1}
      //       opacity={0.5}
      //       speed={0.4}
      //     >

      //       <About />
      //       {/* <Image
      //         alt="cloud"
      //         src={codingGif}
      //         // width={500}
      //         // height={300}
      //         layout="intrinsic"
      //       /> */}
      //     </ParallaxLayer>

      //     <ParallaxLayer
      //       offset={0.9}
      //       speed={0.5}
      //       factor={1.5}

      //     >
      //       <Projects />

      //     </ParallaxLayer>

      //     <ParallaxLayer
      //       offset={2.3}
      //       speed={0.3}
      //       factor={0.5}

      //     >
      //       <Contact />

      //     </ParallaxLayer>
      //   </Parallax>
      //   <ThemeProvider theme={theme}>
      //     {/* <div className="jumpToMail" onClick={() => jumpTo("mail-section")}>

      //     <Fab color="primary" aria-label="add" data-fab-mail>
      //       <MailOutlineIcon />
      //     </Fab>
      //     </div> */}
      //   </ThemeProvider>